#include "ui/CubeController.h"

#include "ui/CubeLayout.h"

#include <algorithm>

namespace rubik::ui {

MoveDescription describeMove(Move move) noexcept {
  MoveDescription out;
  switch (face(move)) {
    case Face::U: out.face = "UP"; break;
    case Face::R: out.face = "RIGHT"; break;
    case Face::F: out.face = "FRONT"; break;
    case Face::D: out.face = "DOWN"; break;
    case Face::L: out.face = "LEFT"; break;
    case Face::B: out.face = "BACK"; break;
  }
  switch (turns(move)) {
    case 0: out.turn = "CLOCKWISE"; break;
    case 1: out.turn = "180 DEGREES"; break;
    default: out.turn = "COUNTER-CLOCKWISE"; break;
  }
  return out;
}

CubeController::CubeController() = default;

void CubeController::enqueue(Move move) { queue_.push_back(move); }

void CubeController::enqueue(const std::vector<Move>& moves) {
  queue_.insert(queue_.end(), moves.begin(), moves.end());
}

void CubeController::startNext() {
  if (queue_.empty()) {
    animation_.active = false;
    animation_.angleRadians = 0.0f;
    solutionDelta_ = 0;
    return;
  }
  animation_.active = true;
  animation_.move = queue_.front();
  animation_.angleRadians = 0.0f;
  queue_.pop_front();
  elapsed_ = 0.0;
}

void CubeController::update(double deltaSeconds) {
  if (!animation_.active) {
    // Playback feeds the queue one move at a time so that pausing takes effect
    // immediately rather than after everything already queued has run.
    if (queue_.empty() && playing_ && !solutionComplete()) {
      queue_.push_back(solution_[static_cast<std::size_t>(solutionIndex_)]);
      solutionDelta_ = 1;
    }
    if (queue_.empty()) return;
    startNext();
    if (!animation_.active) return;
  }

  // A half turn is given half again the time of a quarter turn: turning 180
  // degrees in the same period reads as twice the speed and is hard to follow.
  const double duration =
      (turns(animation_.move) == 1 ? 1.5 : 1.0) / std::max(movesPerSecond_, 0.1);

  elapsed_ += deltaSeconds;
  const double fraction = std::clamp(elapsed_ / duration, 0.0, 1.0);

  // Smoothstep: the layer eases in and out rather than starting and stopping
  // abruptly. Interpolating the angle and letting the renderer build the
  // quaternion from it is equivalent to slerping between the two orientations,
  // because the rotation is about a fixed axis.
  const double eased = fraction * fraction * (3.0 - 2.0 * fraction);
  animation_.angleRadians =
      static_cast<float>(eased) * moveAngleRadians(animation_.move);

  if (fraction < 1.0) return;

  // The animation finished, so now -- and only now -- the model changes.
  cube_.apply(animation_.move);
  // One commit path for forwards, backwards and hand-made turns alike.
  const int next = solutionIndex_ + solutionDelta_;
  if (solutionDelta_ != 0 && next >= 0 &&
      next <= static_cast<int>(solution_.size())) {
    solutionIndex_ = next;
  }
  solutionDelta_ = 0;
  animation_.active = false;
  animation_.angleRadians = 0.0f;

  if (playing_ && solutionComplete()) playing_ = false;

  // Deliberately not starting the next move here: at most one move is committed
  // per update, so a long stall cannot flash several turns past in one frame.
}

void CubeController::setCube(const Cube& cube) {
  reset();
  cube_ = cube;
}

void CubeController::reset() {
  cube_.reset();
  solutionStart_.reset();
  queue_.clear();
  animation_ = Animation{};
  solutionDelta_ = 0;
  elapsed_ = 0.0;
  solution_.clear();
  solutionIndex_ = 0;
  playing_ = false;
  lastScramble_.clear();
}

void CubeController::cancelPending() {
  queue_.clear();
  animation_ = Animation{};
  solutionDelta_ = 0;
  elapsed_ = 0.0;
  playing_ = false;
}

std::vector<Move> CubeController::scramble(int moveCount, std::uint64_t seed) {
  // Generated by the core's own scrambler, so the GUI and the CLI produce the
  // same sequence for the same seed and there is no second implementation to
  // keep honest.
  Cube probe;
  lastScramble_ = probe.scramble(moveCount, seed);

  cancelPending();
  solution_.clear();
  solutionIndex_ = 0;
  enqueue(lastScramble_);
  return lastScramble_;
}

void CubeController::loadSolution(const std::vector<Move>& moves) {
  solution_ = moves;
  solutionIndex_ = 0;
  playing_ = false;
  // Remembered here rather than reconstructed later: after a few steps the
  // cube no longer knows where it started.
  solutionStart_ = cube_;
}

void CubeController::clearSolution() {
  solution_.clear();
  solutionIndex_ = 0;
  playing_ = false;
}

void CubeController::play() {
  if (solution_.empty() || solutionComplete()) return;
  playing_ = true;
}

void CubeController::pause() { playing_ = false; }

void CubeController::stepForward() {
  if (solution_.empty() || solutionComplete()) return;
  if (busy()) return;  // one at a time, so progress stays legible
  playing_ = false;
  queue_.push_back(solution_[static_cast<std::size_t>(solutionIndex_)]);
  solutionDelta_ = 1;
}

void CubeController::stepBackward() {
  if (solution_.empty() || solutionIndex_ <= 0) return;
  if (busy()) return;
  playing_ = false;
  // Undoing a move is just its inverse, animated the same way -- so going back
  // obeys the same invariant as going forward, and the cube is never left part
  // way through a turn.
  queue_.push_back(
      inverse(solution_[static_cast<std::size_t>(solutionIndex_ - 1)]));
  solutionDelta_ = -1;
}

void CubeController::restartSolution() {
  if (solution_.empty()) return;
  // Abandons anything in flight without committing it, so the cube lands on a
  // whole number of moves before being replaced wholesale.
  cancelPending();
  cube_ = solutionStart_;
  solutionIndex_ = 0;
}

std::optional<Move> CubeController::nextSolutionMove() const noexcept {
  if (solution_.empty() || solutionComplete()) return std::nullopt;
  return solution_[static_cast<std::size_t>(solutionIndex_)];
}

std::optional<Move> CubeController::animatingSolutionMove() const noexcept {
  if (!animation_.active || solutionDelta_ == 0) return std::nullopt;
  return animation_.move;
}

void CubeController::setSpeed(double movesPerSecond) {
  movesPerSecond_ = std::clamp(movesPerSecond, 0.5, 30.0);
}

}  // namespace rubik::ui
