#pragma once

#include "core/Error.h"
#include "core/Move.h"

#include <cassert>
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace rubik {

/// An admissible heuristic stored as a flat array of exact distances.
///
/// Each entry is the exact number of moves needed to solve a *relaxed* version
/// of the problem -- one that tracks only a pair of coordinates and ignores
/// everything else. Since the real problem is at least as hard, the value can
/// never overestimate, which is what admissibility requires and what lets the
/// search prune a branch the moment `depth + heuristic` exceeds the bound.
///
/// The table is generated by breadth-first search backwards from the goal.
/// That is only valid because every move set used here is closed under
/// inversion -- {U, U2, U'} contains each element's inverse, and R2 is its own
/// inverse -- so the distance from the goal equals the distance to it.
///
/// Entries are bytes rather than nibbles. Nibble packing would halve the
/// footprint, and NibbleArray is ready for it, but these four tables total under
/// 4 MB and the correct order is to measure before trading clarity for size.
/// (The Korf databases are a different matter: there packing is the difference
/// between 42 MB and 84 MB, and it is not optional.)
class PruningTable {
 public:
  static constexpr std::uint8_t kUnvisited = 0xFF;

  PruningTable() = default;

  [[nodiscard]] std::uint8_t get(std::uint32_t index) const noexcept {
    assert(index < data_.size());
    return data_[index];
  }

  [[nodiscard]] std::uint32_t size() const noexcept {
    return static_cast<std::uint32_t>(data_.size());
  }
  [[nodiscard]] std::uint8_t maxDistance() const noexcept { return maxDistance_; }
  [[nodiscard]] const std::string& name() const noexcept { return name_; }
  [[nodiscard]] std::size_t byteSize() const noexcept { return data_.size(); }

  /// Builds the table by breadth-first search outward from `goalIndex`.
  ///
  /// `transition(index, move)` must return the index reached by applying `move`
  /// to `index`. Throws if any state turns out to be unreachable, which would
  /// mean the index space and the move set disagree -- a bug worth failing on
  /// rather than silently returning a wrong heuristic.
  template <typename TransitionFn>
  static PruningTable build(std::string name, std::uint32_t size,
                            std::uint32_t moveMask, std::uint32_t goalIndex,
                            TransitionFn transition);

 private:
  std::string name_;
  std::vector<std::uint8_t> data_;
  std::uint8_t maxDistance_ = 0;
};

template <typename TransitionFn>
PruningTable PruningTable::build(std::string name, std::uint32_t size,
                                 std::uint32_t moveMask,
                                 std::uint32_t goalIndex,
                                 TransitionFn transition) {
  PruningTable table;
  table.name_ = std::move(name);
  table.data_.assign(size, kUnvisited);
  table.data_[goalIndex] = 0;

  std::vector<std::uint32_t> frontier;
  std::vector<std::uint32_t> next;
  frontier.push_back(goalIndex);

  std::uint32_t visited = 1;
  std::uint8_t depth = 0;

  while (!frontier.empty()) {
    ++depth;
    next.clear();
    for (const std::uint32_t state : frontier) {
      for (int m = 0; m < kNumMoves; ++m) {
        if (((moveMask >> m) & 1u) == 0u) continue;
        const std::uint32_t successor = transition(state, static_cast<Move>(m));
        if (table.data_[successor] != kUnvisited) continue;
        table.data_[successor] = depth;
        ++visited;
        next.push_back(successor);
      }
    }
    frontier.swap(next);
  }

  table.maxDistance_ = static_cast<std::uint8_t>(depth - 1);

  if (visited != size) {
    throw Error("pruning table '" + table.name_ + "' reached only " +
                std::to_string(visited) + " of " + std::to_string(size) +
                " states; the coordinate space and move set are inconsistent");
  }
  return table;
}

}  // namespace rubik
